# Generated by Django 6.0.3 on 2026-04-22 16:51

import django.db.models.deletion
from django.db import migrations, models


def _backfill_active_workspace(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Workspace = apps.get_model('projects', 'Workspace')
    for user in User.objects.all():
        personal = Workspace.objects.filter(owner=user, is_personal=True).first()
        if personal:
            user.active_workspace = personal
            user.save(update_fields=['active_workspace'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workspace_rewrite'),
        ('users', '0006_phase1_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='projects.workspace'),
        ),
        migrations.RunPython(
            code=_backfill_active_workspace,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
