# Generated by Django 4.2.17 on 2026-04-21 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField()),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_assigned', models.PositiveIntegerField(default=0)),
                ('comments_posted', models.PositiveIntegerField(default=0)),
                ('logged_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_metrics', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_metrics',
                'ordering': ['metric_date'],
                'indexes': [models.Index(fields=['user', 'metric_date'], name='user_metric_user_id_8ead48_idx'), models.Index(fields=['project', 'metric_date'], name='user_metric_project_fe9c8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('in_progress_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('total_story_points', models.PositiveIntegerField(default=0)),
                ('completed_story_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='projects.sprint')),
            ],
            options={
                'db_table': 'task_snapshots',
                'ordering': ['snapshot_date'],
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='task_snapsh_project_f9c813_idx'), models.Index(fields=['sprint', 'snapshot_date'], name='task_snapsh_sprint__d183db_idx')],
            },
        ),
    ]
