# Generated by Django 6.0.3 on 2026-04-22 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_phase1_indexes'),
        ('tasks', '0003_add_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_id', 'created_at'], name='activity_entity_time_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', 'deleted_at'], name='comment_task_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'deleted_at'], name='task_project_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='task_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status', 'deleted_at'], name='task_due_status_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['sprint', 'status'], name='task_sprint_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['task', 'logged_date'], name='timelog_task_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'logged_date'], name='timelog_user_date_idx'),
        ),
    ]
