# Generated by Django 4.2.17 on 2026-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_phase1_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('sprint', 'Sprint'), ('comment', 'Comment'), ('workspace', 'Workspace')], max_length=10),
        ),
    ]
