# Generated by Django 4.2.17 on 2026-04-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_workspace_rewrite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspace',
            new_name='workspaces_owner_i_a3d0a5_idx',
            old_name='ws_owner_personal_idx',
        ),
        migrations.RenameIndex(
            model_name='workspace',
            new_name='workspaces_delete__363b8a_idx',
            old_name='ws_delete_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinvitation',
            new_name='workspace_i_workspa_0bb032_idx',
            old_name='wsinv_ws_state_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinvitation',
            new_name='workspace_i_email_9faa6b_idx',
            old_name='wsinv_email_idx',
        ),
    ]
