# Generated by Django 6.0.3 on 2026-04-22 16:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _backfill_ws_member_roles(apps, schema_editor):
    WorkspaceMember = apps.get_model('projects', 'WorkspaceMember')
    Workspace = apps.get_model('projects', 'Workspace')
    for ws in Workspace.objects.all():
        WorkspaceMember.objects.filter(workspace=ws, user_id=ws.owner_id).update(role='OWNER')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_phase1_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('link', 'Link')], max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role_to_grant', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workspace_invitations',
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='delete_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.RunPython(
            code=_backfill_ws_member_roles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'is_personal'], name='ws_owner_personal_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['delete_scheduled_for'], name='ws_delete_scheduled_idx'),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invites_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.workspace'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', 'accepted_at', 'revoked_at'], name='ws_invite_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['email'], name='ws_invite_email_idx'),
        ),
    ]
